# Generated by Django 5.1.1 on 2024-09-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_creator_product_last_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
