# Generated by Django 5.1.1 on 2024-09-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='photo_url',
        ),
    ]
